FROM zdzserver/docker-runtime:php7.4-fpm-ubuntu

## 切换目录
WORKDIR /var/www

## 拷贝代码
COPY . .

## 删除多余
# laravel
RUN rm -rf storage/logs/*.log && rm -rf storage/framework/cache/data/* && rm -rf bootstrap/cache/*
RUN rm -rf .git && rm -rf .idea

## 修改权限
RUN chown -R www-data:www-data /var/www/

## 环境变量
## nginx header Access-Control-Allow-Origin 的值
# ENV NGINX_HEADER_ALLOW_ORIGIN="*"
## nginx header Access-Control-Allow-Headers 的值
# ENV NGINX_HEADER_ALLOW_HEADERS="*"
# OPTIONS请求不快速返回，默认 true
# ENV NGINX_OPTIONS_RETURN=false
# laravel 定时调度，默认true，需开启cron
# ENV CRON_LARAVEL_SCHEDULE=false

## 根据需要启动cron、laravel-queue, laravel-socket, $otherCommand，无顺序要求
## 默认以root用户运行，若想以www-data运行，则写成这样：[ "su - www-data -s /bin/bash -c '$otherCommand'" ]
## CMD ["cron", "laravel-queue", "$otherCommand", "..."]